name: Build GH-Pages
env:
  PUBLISH_DIR: dist/postnl-poc

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: npm i and build
        run: |
          npm i
          npm run build:prod

      # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch ${{env.PUBLISH_DIR}}/.nojekyll

      - name: GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.5.1
        with:
          target_branch: gh-pages
          build_dir: ${{ env.PUBLISH_DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
